### ISSUE TITLE
http handlers panic not caught ?

### ISSUE THREAD

**Issue by mh-cbon** [mitchellh/panicwrap#17]
Hi!

Working on a webservice written in go,
I trigger a panic from an http handler,
it generates a log on stderr,
but that is not caught by panicwrap.

The log output is,
```sh
2017/03/22 14:19:33 http: panic serving 127.0.0.1:35200: NOOOOOO
goroutine 43 [running]:
net/http.(*conn).serve.func1(0xc42031e5a0)
	/home/mh-cbon/.gvm/gos/go1.8/src/net/http/server.go:1721 +0xd0
panic(0x775c60, 0xc420314d00)
	/home/mh-cbon/.gvm/gos/go1.8/src/runtime/panic.go:489 +0x2cf
github.com/mh-cbon/backup/api.(*ActiveTasksEP).running(0xc4201f6f30, 0x7f41b44fb018, 0xc4202db9e0, 0xc4200e2e00)
	/home/mh-cbon/gow/src/github.com/mh-cbon/backup/api/tasks.go:226 +0x170
github.com/mh-cbon/backup/api.(*ActiveTasksEP).(github.com/mh-cbon/backup/api.running)-fm(0x7f41b44fb018, 0xc4202db9e0, 0xc4200e2e00)
	/home/mh-cbon/gow/src/github.com/mh-cbon/backup/api/tasks.go:43 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420203d10, 0x7f41b44fb018, 0xc4202db9e0, 0xc4200e2e00)
	/home/mh-cbon/.gvm/gos/go1.8/src/net/http/server.go:1942 +0x44
github.com/mh-cbon/backup/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42009aeb0, 0x7f41b44fb018, 0xc4202db9e0, 0xc4200e2e00)
	/home/mh-cbon/gow/src/github.com/mh-cbon/backup/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/mh-cbon/backup/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc42011c240, 0x7f41b44fb018, 0xc4202db9e0, 0xc4200e2c00)
	/home/mh-cbon/gow/src/github.com/mh-cbon/backup/vendor/github.com/gorilla/handlers/cors.go:118 +0x5b2
github.com/mh-cbon/backup/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x99f1e0, 0xc420090010, 0x99e220, 0xc42011c240, 0x9a39e0, 0xc420322b60, 0xc4200e2c00)
	/home/mh-cbon/gow/src/github.com/mh-cbon/backup/vendor/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/mh-cbon/backup/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc420137d60, 0x9a39e0, 0xc420322b60, 0xc4200e2c00)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc42022a000, 0x9a39e0, 0xc420322b60, 0xc4200e2c00)
	/home/mh-cbon/.gvm/gos/go1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42031e5a0, 0x9a3fa0, 0xc420087880)
	/home/mh-cbon/.gvm/gos/go1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/home/mh-cbon/.gvm/gos/go1.8/src/net/http/server.go:2668 +0x2ce
```

Is it desired ? 

In my case i d like to catch them, 
even though the program is not dying because 
I track those for monitoring purpose (https://github.com/mh-cbon/report-panic).

Do you have any thoughts to share so i can decide what to do next?

Forgot some more details for your convenience,

```sh
cmd prove it outs to stderr $ go run main.go 2>/dev/null
go version go1.8 linux/amd64
````

**Comment by apparentlymart** [comment]
Hi @mh-cbon!

`panicwrap` is focused on dealing with _unhandled_ panics that cause the process to abort, so reacting to panics within HTTP handlers is not really in its scope.

Over in golang/go#16542 there was some discussion about a possible way to disable the behavior of capturing and handling panics in the HTTP library, which was ultimately rejected. However, there is [a comment on that issue](https://github.com/golang/go/issues/16542#issuecomment-246549902) that gives an example of wrapping a handler to do some custom behavior if the "real" handler panics, which I think would get you what you want here.
